apiVersion: v2
name: linkshort
description: A Helm chart for LinkShort URL Shortener microservices
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - url-shortener
  - microservices
  - golang
  - nextjs
maintainers:
  - name: aditer00
