{{- if .Values.urlService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "linkshort.fullname" . }}-url-service
  labels:
    {{- include "linkshort.labels" . | nindent 4 }}
    app.kubernetes.io/component: url-service
spec:
  replicas: {{ .Values.urlService.replicaCount }}
  selector:
    matchLabels:
      {{- include "linkshort.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: url-service
  template:
    metadata:
      labels:
        {{- include "linkshort.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: url-service
    spec:
      containers:
        - name: url-service
          image: "{{ .Values.urlService.image.repository }}:{{ .Values.urlService.image.tag | default .Values.global.imageTag }}"
          imagePullPolicy: {{ .Values.urlService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.urlService.service.port }}
          env:
            - name: PORT
              value: {{ .Values.urlService.service.port | quote }}
            - name: STORAGE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "linkshort.fullname" . }}-config
                  key: STORAGE_TYPE
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "linkshort.fullname" . }}-config
                  key: REDIS_URL
            - name: ANALYTICS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "linkshort.fullname" . }}-config
                  key: ANALYTICS_SERVICE_URL
          resources:
            {{- toYaml .Values.urlService.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.urlService.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.urlService.service.port }}
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "linkshort.fullname" . }}-url-service
  labels:
    {{- include "linkshort.labels" . | nindent 4 }}
    app.kubernetes.io/component: url-service
spec:
  type: {{ .Values.urlService.service.type }}
  ports:
    - port: {{ .Values.urlService.service.port }}
      targetPort: {{ .Values.urlService.service.port }}
  selector:
    {{- include "linkshort.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: url-service
{{- end }}
